CREATE TABLE channels(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,agent_id uuid NOT NULL REFERENCES agents(id),type varchar(20) NOT NULL CHECK(type IN('whatsapp','web','api')),display_name varchar(120) NOT NULL,phone_number varchar(40),external_channel_id text,service_instance_id text,status varchar(30) NOT NULL,connected_at timestamptz,last_seen_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(workspace_id,id));
CREATE TABLE conversations(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,agent_id uuid NOT NULL REFERENCES agents(id),channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE,external_user_id text NOT NULL,status varchar(10) NOT NULL CHECK(status IN('open','closed')),mode varchar(10) NOT NULL CHECK(mode IN('agent','human')),environment varchar(10) NOT NULL DEFAULT 'production' CHECK(environment IN('production','test')),assigned_user_id uuid REFERENCES users(id),started_at timestamptz NOT NULL DEFAULT now(),last_message_at timestamptz NOT NULL DEFAULT now(),closed_at timestamptz,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX conversations_one_open_external_user_idx ON conversations(channel_id,external_user_id) WHERE status='open';
CREATE TABLE messages(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,channel_id uuid,sender_type varchar(10) NOT NULL CHECK(sender_type IN('customer','agent','human','system')),content_type varchar(20) NOT NULL,content jsonb NOT NULL,external_message_id text,provider varchar(30),status varchar(20) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(channel_id,external_message_id));
CREATE TABLE api_keys(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,prefix varchar(32) NOT NULL UNIQUE,hash char(64) NOT NULL,last_four char(4) NOT NULL,name varchar(120) NOT NULL,scopes jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),last_used_at timestamptz,revoked_at timestamptz);
CREATE TABLE api_sessions(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,agent_id uuid NOT NULL REFERENCES agents(id),external_user_id text NOT NULL,token_hash char(64) NOT NULL UNIQUE,metadata jsonb NOT NULL DEFAULT '{}',expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE usage_records(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,metric varchar(50) NOT NULL,quantity bigint NOT NULL CHECK(quantity>=0),environment varchar(10) NOT NULL,recorded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_logs(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id),event varchar(80) NOT NULL,resource_type varchar(50) NOT NULL,resource_id uuid,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX conversations_workspace_idx ON conversations(workspace_id,last_message_at DESC);CREATE INDEX messages_conversation_idx ON messages(workspace_id,conversation_id,created_at);CREATE INDEX channels_workspace_idx ON channels(workspace_id,id);CREATE INDEX usage_workspace_metric_idx ON usage_records(workspace_id,metric,recorded_at);CREATE INDEX audit_workspace_idx ON audit_logs(workspace_id,created_at DESC);
